export default {
    GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
    DRIVER_STATUS: "DRIVER_STATUS",
    GET_INPUT: "GET_INPUT",
    GET_DRIVER_INFORMATION: "GET_DRIVER_INFORMATION",
    GET_SOCKET_ID: "GET_SOCKET_ID",
    POST_DRIVER_LOCATION: "POST_DRIVER_LOCATION",
    NEW_BOOKING: "NEW_BOOKING",
    IN_ROUTE_TO: "IN_ROUTE_TO",
    WATCH_DRIVER_LOCATION: "WATCH_DRIVER_LOCATION",
    MARKER_LOCATION: "MARKER_LOCATION",
    NEAR_DRIVER_ALERTED: "NEAR_DRIVER_ALERTED",
    DECLINE_RIDE: "DECLINE_RIDE"
};