export default {
    GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
    GET_INPUT: "GET_INPUT",
    GET_DRIVER_INFORMATION: "GET_DRIVER_INFORMATION",
    GET_SOCKET_ID: "GET_SOCKET_ID",
    POST_DRIVER_LOCATION: "POST_DRIVER_LOCATION"
};