export default {
   GET_INPUT: "GET_INPUT",
   AUTH_USER: "AUTH_USER",
   UNAUTH_USER: "UNAUTH_USER",
   // ADD_ALERT: "ADD_ALERT",
   REMOVE_ALERT: "REMOVE_ALERT",
   NEEDS_PROFILE: "NEEDS_PROFILE",
   CREATE_USER_PROFILE: "CREATE_USER_PROFILE",
   CREATE_VEHICLE_PROFILE: "CREATE_VEHICLE_PROFILE",
   NAV_TO_CAR_PROFILE: "NAV_TO_CAR_PROFILE",
   IS_LOGGING_IN: "IS_LOGGING_IN",
   IS_SIGNING_UP: "IS_SIGNING_UP",
   USER_PROFILE_CREATED: "USER_PROFILE_CREATED"
};