export default {
   GET_INPUT: "GET_INPUT",
   AUTH_USER: "AUTH_USER",
   UNAUTH_USER: "UNAUTH_USER",
   NEEDS_PROFILE: "NEEDS_PROFILE",
   CREATE_USER_PROFILE: "CREATE_USER_PROFILE",
   CREATE_VEHICLE_PROFILE: "CREATE_VEHICLE_PROFILE",
   NAV_TO_CAR_PROFILE: "NAV_TO_CAR_PROFILE",
   IS_LOGGING_IN: "IS_LOGGING_IN",
   IS_SIGNING_UP: "IS_SIGNING_UP",
   USER_PROFILE_CREATED: "USER_PROFILE_CREATED",
   CLEAR_PROFILE: "CLEAR_PROFILE",
   VEHICLE_GARAGE: "VEHICLE_GARAGE",
   GET_DRIVER_INFORMATION: "GET_DRIVER_INFORMATION",
   IS_LOADING: "IS_LOADING",
   PASSWORD_RESET_MESSAGE: "PASSWORD_RESET_MESSAGE",
   CLEAR_PASSWORD_RESET_MESSAGE: "CLEAR_PASSWORD_RESET_MESSAGE"
};