export default {
   GET_INPUT: "GET_INPUT",
   AUTH_USER: "AUTH_USER",
   UNAUTH_USER: "UNAUTH_USER",
   // ADD_ALERT: "ADD_ALERT",
   REMOVE_ALERT: "REMOVE_ALERT",
   NEEDS_PROFILE: "NEEDS_PROFILE"

};