export default {
   UNAUTH_USER:"UNAUTH_USER",
   GET_DRIVER_INFORMATION: "GET_DRIVER_INFORMATION",
   EDITTING_PROFILE: "EDITTING_PROFILE",
   USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
   DRIVER_RIDE_HISTORY: "DRIVER_RIDE_HISTORY",
   UPDATE_VEHICLE_TYPE: "UPDATE_VEHICLE_TYPE",
   SELECT_VEHICLE_INFO: "SELECT_VEHICLE_INFO",
   EDITTING_VEHICLE_PROFILE: "EDITTING_VEHICLE_PROFILE",
   IS_VEHICLES_LOADING: "IS_VEHICLES_LOADING",
   DRIVER_IMAGE_UPLOADED: "DRIVER_IMAGE_UPLOADED",
   PROFILE_PIC_PATH: "PROFILE_PIC_PATH"
};