export default {
   UNAUTH_USER:"UNAUTH_USER",
   GET_DRIVER_INFORMATION: "GET_DRIVER_INFORMATION",
   EDITTING_PROFILE: "EDITTING_PROFILE",
   USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
   DRIVER_RIDE_HISTORY: "DRIVER_RIDE_HISTORY",
   UPDATE_VEHICLE_TYPE: "UPDATE_VEHICLE_TYPE"
};