export default {
    GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
    DRIVER_STATUS: "DRIVER_STATUS",
    // IN_ROUTE_TO: "IN_ROUTE_TO",
    WATCH_DRIVER_LOCATION: "WATCH_DRIVER_LOCATION",
    MARKER_LOCATION: "MARKER_LOCATION",
    GET_PASSENGER_ROUTES: "GET_PASSENGER_ROUTES",
};