export default {
    // GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
    // UPDATE_BOOKING_DETAILS: "UPDATE_BOOKING_DETAILS",
    // DRIVER_STATUS: "DRIVER_STATUS",
    // IN_ROUTE_TO: "IN_ROUTE_TO",
    WATCH_DRIVER_LOCATION: "WATCH_DRIVER_LOCATION",
    MARKER_LOCATION: "MARKER_LOCATION",
    // NEAR_DRIVER_ALERTED: "NEAR_DRIVER_ALERTED",
    GET_DISTANCE_FROM: "GET_DISTANCE_FROM",
    GET_PICKUP_ROUTE: "GET_PICKUP_ROUTE",
    PICKUP_ARRIVING_ALERTED: "PICKUP_ARRIVING_ALERTED",
    DISTANCE_FROM_PICKUP: "DISTANCE_FROM_PICKUP"
};