export default {
    GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
    // DRIVER_STATUS: "DRIVER_STATUS",
    // IN_ROUTE_TO: "IN_ROUTE_TO",
    WATCH_DRIVER_LOCATION: "WATCH_DRIVER_LOCATION",
    // MARKER_LOCATION: "MARKER_LOCATION",
    // NEAR_DRIVER_ALERTED: "NEAR_DRIVER_ALERTED",
    GET_DISTANCE_FROM: "GET_DISTANCE_FROM",
    // UPDATE_BOOKING_DETAILS: "UPDATE_BOOKING_DETAILS",
    GET_DROP_OFF_ROUTE: "GET_DROP_OFF_ROUTE"
};